### 根據範例檔案的結果：

1. 取出班次一的每一個時間
2. 將班次一的每一個時間用一種資料型態保存
3. 將班次一到五與其所有時間用一種資料型態個別保存

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("example.csv")

In [3]:
df

,序號,路線編號,起訖站,平/假日,站名,班次1,班次2,班次3,班次4,班次5,班次6,班次7,班次8,班次9,班次10,班次11,是否單邊停靠
0,1,51,香山區公所—火車站（先經中山路）,平日,香山區公所,06:30,07:50,09:10,10:30,12:00,13:20,14:40,16:10,18:10,19:40,21:10,否
1,2,51,香山區公所—火車站（先經中山路）,平日,香山國小,06:32,07:52,09:12,10:32,12:02,13:22,14:42,16:12,18:12,19:42,21:12,否
2,3,51,香山區公所—火車站（先經中山路）,平日,聖德宮,06:33,07:53,09:13,10:33,12:03,13:23,14:43,16:13,18:13,19:43,21:13,否
3,4,51,香山區公所—火車站（先經中山路）,平日,頂埔社區,06:34,07:55,09:15,10:35,12:05,13:24,14:45,16:15,18:15,19:45,21:15,否
4,5,51,香山區公所—火車站（先經中山路）,平日,大鵬新城,06:36,07:57,09:17,10:37,12:07,13:26,14:47,16:17,18:17,19:47,21:17,單邊停靠
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,34,51,香山區公所—火車站（先經中山路）,假日,信義幼稚園,07:49,09:43,11:03,12:23,13:53,15:33,16:53,18:13,19:33,20:53,22:03,單邊停靠
72,35,51,香山區公所—火車站（先經中山路）,假日,頂埔社區,07:51,09:45,11:05,12:25,13:55,15:35,16:55,18:15,19:35,20:55,22:05,否
73,36,51,香山區公所—火車站（先經中山路）,假日,聖德宮,07:53,09:47,11:07,12:27,13:57,15:37,16:57,18:17,19:37,20:57,22:07,否
74,37,51,香山區公所—火車站（先經中山路）,假日,香山國小,07:54,09:49,11:09,12:29,13:59,15:39,16:59,18:19,19:39,20:59,22:09,否
75,38,51,香山區公所—火車站（先經中山路）,假日,香山區公所,07:55,09:50,11:10,12:30,14:00,15:40,17:00,18:20,19:40,21:00,22:10,否

In [4]:
print(df['班次1'])

0     06:30
1     06:32
2     06:33
3     06:34
4     06:36
      ...
71    07:49
72    07:51
73    07:53
74    07:54
75    07:55
Name: 班次1, Length: 76, dtype: object

In [5]:
df2 = pd.DataFrame(df['班次1'])

In [6]:
df2

      班次1
0   06:30
1   06:32
2   06:33
3   06:34
4   06:36
..    ...
71  07:49
72  07:51
73  07:53
74  07:54
75  07:55

[76 rows x 1 columns]

In [11]:
df3 = pd.DataFrame(df, columns=['班次1','班次2', '班次3','班次4', '班次5'])

In [12]:
df3

      班次1    班次2    班次3    班次4    班次5
0   06:30  07:50  09:10  10:30  12:00
1   06:32  07:52  09:12  10:32  12:02
2   06:33  07:53  09:13  10:33  12:03
3   06:34  07:55  09:15  10:35  12:05
4   06:36  07:57  09:17  10:37  12:07
..    ...    ...    ...    ...    ...
71  07:49  09:43  11:03  12:23  13:53
72  07:51  09:45  11:05  12:25  13:55
73  07:53  09:47  11:07  12:27  13:57
74  07:54  09:49  11:09  12:29  13:59
75  07:55  09:50  11:10  12:30  14:00

[76 rows x 5 columns]